import React, { useState, useEffect, useRef } from 'react'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link';
import NavComponent from '../../components/NavComponent';
import { use100vh } from 'react-div-100vh'
import useWindowDimensions from './../../components/DimensionsHook';

export default function Contact() {

  const hh2 = use100vh()
  const { height, width } =  useWindowDimensions();
  const isMobile = width < 620 || (typeof document != 'undefined' && window.innerWidth < 620);

  return (
    <>
    <div className="grain"></div>
    <div className={styles.container + " loadingScreen"} style={{ height: isMobile ? hh2 : '100vh' }}>
      <Head>
        <title>Pacific Interlude</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
      </Head>

      <div className={`d-flex w-100 h-100 flex-column ${styles.body}`}>
        <NavComponent />
        <div className={`d-flex flex-column p-4 ${styles.about}`} style={{ maxHeight: 'calc(100% - 3rem)' }}>
          <h5>contact us</h5>
          <div className={`d-flex align-items-center`}>
            <p><a href="mailto:work@pacificinterlude.com">work@pacificinterlude.com</a></p>
          </div>
          <h5>socials</h5>
          <div className={`d-flex align-items-center`}>
            <p><a href="https://www.instagram.com/pacificinterlude">@pacificinterlude</a></p>
          </div>
        </div>
      </div>
    </div>
    </>
  )
}