import React, { useState, useEffect, useRef } from 'react'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link';
import NavComponent from '../../components/NavComponent';
import axios from 'axios';

export default function Projects() {

  const [albums, setAlbums] = useState(null)

  const fetchAlbums = async () => {
      try {
          const res = await axios.get("/api/albums/fetch");
          setAlbums(res.data);
      } catch (e) {
          console.error(e)
      }
  }

  useEffect(() => {
      if (!albums) fetchAlbums();
  }, [])

  return (
    <>
    <div className="grain"></div>
    <div className={styles.container + " loadingScreen"}>
      <Head>
        <title>Pacific Interlude</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
      </Head>

      <div className={`d-flex w-100 h-100 flex-column ${styles.body}`}>
        <NavComponent />
        <div className={`d-flex flex-wrap p-4`} style={{ maxHeight: 'calc(100% - 3rem)' }}>
          {albums && albums.map((album) => {
            if (album.uploads.length > 0 && album.id !== 1) {
              return (
                <div className={`d-flex p-2`} style={{ maxHeight: '50rem' }}>
                  <img src={album.uploads[0].img_src} className={`h-100`} style={{ objectFit: 'cover', width: 'auto' }} />
                </div>
              )
            }
          })}
        </div>
      </div>
    </div>
    </>
  )
}