import React, { useState, useEffect, useRef } from 'react'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link';
import NavComponent from '../../components/NavComponent';
import { use100vh } from 'react-div-100vh'
import useWindowDimensions from './../../components/DimensionsHook';

export default function About() {

  const hh2 = use100vh()
  const { height, width } =  useWindowDimensions();
  const isMobile = width < 620 || (typeof document != 'undefined' && window.innerWidth < 620);

  return (
    <>
    <div className="grain"></div>
    <div className={styles.container + " loadingScreen"} style={{ height: isMobile ? hh2 : '100vh' }}>
      <Head>
        <title>Pacific Interlude</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
      </Head>

      <div className={`d-flex w-100 h-100 flex-column ${styles.body}`}>
        <NavComponent />
        <div className={`d-flex flex-column p-4 ${styles.about}`} style={{ maxHeight: 'calc(100% - 3rem)' }}>
          <p>For 6 years, Pacific Interlude has been leading the way in brand transformation.</p>
          <p>With a blend of creative and strategic vision, we have been turning brands into iconic benchmarks that both define and transcend their time.</p>
          <p>Our expertise in brand work, book design, photography, film, and editorial, allows us to continuously challenge the status quo and bring a fresh and fearless approach to every project.</p>
          
          <br />
          <h5>services</h5>
          <p>
            <i className="fas fa-angle-right"></i> content creation<br />
            <i className="fas fa-angle-right"></i> influencer marketing<br />
            <i className="fas fa-angle-right"></i> brand collaborations<br />
            <i className="fas fa-angle-right"></i> digital strategy<br />
            <i className="fas fa-angle-right"></i> pr
          </p>
        </div>
      </div>

     
    </div>
    </>
  )
}
