import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Splide, SplideSlide } from '@splidejs/react-splide';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Splide className='h-100 w-100'>
        <SplideSlide>
          <Image
            className={`d-flex h-100 w-100`}
            src={"/images/lonewolf.jpg"}
            alt={"lonewolf.jpg"}
            loading={"lazy"}
            width={2005}
            height={3024}
          />
        </SplideSlide>
        <SplideSlide>
          <Image
            className={`d-flex h-100 w-100`}
            src={"/images/lonewolf.jpg"}
            alt={"lonewolf.jpg"}
            loading={"lazy"}
            width={2005}
            height={3024}
          />
        </SplideSlide>
      </Splide>

    </div>
  )
}
